# -*- coding: utf-8 -*-
"""EDA Q5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12hDjqpQP3yRc2wDhuLyHB6mZ42794OgR

Q5(a) Board-Ready Recommendations

---


Recommendation 1: Tighten Lending Standards for Low-CIBIL Borrowers

Evidence

The KDE analysis showed that defaulted borrowers have significantly lower average CIBIL scores than performing borrowers. The Poor and Fair CIBIL bands also represented a disproportionately high share of defaults.

Business Impact

If approvals for the lowest CIBIL segment are reduced by 20%, the bank could potentially reduce default incidence by approximately X percentage points and lower expected credit losses by ₹X Crore annually.

Action

Introduce stricter underwriting thresholds for applicants with CIBIL scores below the identified risk threshold and require additional verification or collateral before approval.

---


Recommendation 2: Introduce EMI-to-Income Caps

Evidence

EDA and feature engineering indicated that higher EMI-to-Income Ratios are associated with elevated default risk and higher LGD.

Business Impact

Reducing exposure to borrowers with EMI burdens above 40–50% of income could decrease portfolio default rates by approximately X percentage points and improve recovery outcomes.

Action

Implement a policy cap that restricts loan approval when EMI obligations exceed a predefined percentage of verified monthly income.

---


Recommendation 3: Reprice High-Risk Loan Grades

Evidence

Default rates increased consistently from Grade A to Grade G, confirming that the internal grading system successfully captures borrower risk.

Business Impact

A risk-based pricing strategy could increase risk-adjusted returns while compensating for higher expected losses in lower-grade segments.

Action

Increase interest rate spreads for Grade E–G loans and periodically recalibrate pricing based on observed default performance.

---


Recommendation 4: Restrict High-Risk Loan Purposes

Evidence

The loan-purpose analysis identified three categories with significantly higher default rates than the portfolio average.

Business Impact

Reducing exposure to the highest-risk purposes could lower overall portfolio default rates and reduce annual credit losses by ₹X Crore.

Action

Apply enhanced scrutiny, stricter documentation requirements, or lower exposure limits for loans issued under high-risk purposes.

---


Recommendation 5: Expand Secured Lending and Collateral Coverage

Evidence

The engineered collateral coverage ratio demonstrated an inverse relationship with LGD. Loans with stronger collateral protection experienced lower loss severity.

Business Impact

Increasing the share of adequately secured loans could reduce average LGD by X percentage points and improve recovery rates during default events.

Action

Encourage secured lending products, update collateral valuation processes, and establish minimum collateral coverage thresholds for larger exposures.
"""

