# -*- coding: utf-8 -*-
"""EDA Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TmXrJ3JPcs4AtaliZmSRAjc0YFc9_X9_

Q1(a)
"""

import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt
from scipy.stats import ttest_ind
from statsmodels.stats.outliers_influence import variance_inflation_factor

branch_region_economy = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/branch_region_economy.csv')

collateral_assets = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/collateral_assets.csv')

credit_card_behavior = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/credit_card_behavior.csv')

customer_bureau = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/customer_bureau.csv')

loan_enquiry_bureau = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/loan_enquiry_bureau.csv')

loan_performance = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/loan_performance.csv')

loans_master = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/loans_master.csv')

monthly_emi_track = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/monthly_emi_track.csv')

payment_history = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/payment_history.csv')

tables = {
    "loans_master": loans_master,
    "loan_performance": loan_performance,
    "payment_history": payment_history,
    "monthly_emi_track": monthly_emi_track,
    "loan_enquiry_bureau": loan_enquiry_bureau,
    "customer_bureau": customer_bureau,
    "credit_card_behavior": credit_card_behavior,
    "collateral_assets": collateral_assets,
    "branch_region_economy": branch_region_economy
}

memory_before = sum(
    df.memory_usage(deep=True).sum()
    for df in tables.values()
) / 1024**2

print(memory_before)

for df in tables.values():

    int_cols = df.select_dtypes(include=['int64']).columns
    float_cols = df.select_dtypes(include=['float64']).columns

    df[int_cols] = df[int_cols].apply(
        pd.to_numeric,
        downcast='integer'
    )

    df[float_cols] = df[float_cols].apply(
        pd.to_numeric,
        downcast='float'
    )

memory_after = sum(
    df.memory_usage(deep=True).sum()
    for df in tables.values()
) / 1024**2

print(memory_after)

"""Memory usage was reduced by downcasting integer and floating-point columns to more efficient data types without changing the information content.

Q1(b)
"""

for name, df in tables.items():
    print(name, df['loan_id'].duplicated().sum())

"""Duplicate loan IDs were checked prior to merging to prevent row multiplication during joins."""

master_df = loans_master.copy()

merge_tables = [
    loan_performance,
    payment_history,
    monthly_emi_track,
    loan_enquiry_bureau,
    customer_bureau,
    credit_card_behavior,
    collateral_assets,
    branch_region_economy
]

for table in merge_tables:
    master_df = master_df.merge(
        table,
        on='loan_id',
        how='left'
    )

master_df.shape

"""Left joins were used to preserve all loans while enriching the master table with information from auxiliary datasets.

Q1(c)
"""

# LTV Check
(
    (master_df['ltv_ratio_pct'] < 0)
    |
    (master_df['ltv_ratio_pct'] > 100)
).sum()

master_df['dirty_flag'] = 0

master_df.loc[
    master_df['ltv_ratio_pct'] > 100,
    'dirty_flag'
] = 1

master_df['ltv_ratio_pct'] = (
    master_df['ltv_ratio_pct']
    .clip(upper=100)
)

"""Loan-to-value ratios exceeding 100% were identified as business-rule violations and capped at 100%.

Q1(d) Missing Value Treatment
"""

#Checking missing values
master_df.isnull().sum().sort_values(
    ascending=False
).head(20)

# Required Assignment Variables
master_df['mths_since_last_delinq'] = (
    master_df['mths_since_last_delinq']
    .fillna(999)
)

master_df['mort_acc'] = (
    master_df['mort_acc']
    .fillna(master_df['mort_acc'].median())
)

master_df['emp_length_years'] = (
    master_df['emp_length_years']
    .fillna(master_df['emp_length_years'].median())
)

master_df['il_util_pct'] = (
    master_df['il_util_pct']
    .fillna(0)
)

"""Missing values were classified according to business context. Structural missing values were imputed using business-rule values, while numerical variables were imputed using the median.

Q1(e) Winsorisation
"""

# Identify Skewed Variables
numeric_cols = master_df.select_dtypes(
    include=np.number
)

skewness = (
    numeric_cols
    .skew()
    .abs()
    .sort_values(ascending=False)
)

top6_skewed = skewness.head(6).index.tolist()
top6_skewed

# Winsorise
for col in top6_skewed:

    lower = master_df[col].quantile(0.01)
    upper = master_df[col].quantile(0.99)

    master_df[col] = (
        master_df[col]
        .clip(lower, upper)
    )

"""The six most skewed numerical variables were winsorized at the 1st and 99th percentiles to reduce the influence of extreme outliers.

Q1(f) Feature Engineering
"""

master_df['loan_income_ratio'] = (
    master_df['loan_amnt_inr']
    /
    (master_df['annual_inc_inr'] + 1)
)

master_df['emi_income_burden'] = (
    master_df['installment_inr']
    /
    ((master_df['annual_inc_inr']/12) + 1)
)

master_df['credit_utilization_ratio'] = (
    master_df['revol_bal_inr']
    /
    (master_df['total_rev_hi_lim_inr'] + 1)
)

master_df['payment_efficiency_ratio'] = (
    master_df['total_emi_paid_inr']
    /
    (master_df['total_emi_due_inr'] + 1)
)

master_df['recovery_ratio'] = (
    master_df['recoveries_inr']
    /
    (master_df['loan_amnt_inr'] + 1)
)

"""Additional borrower-risk indicators were engineered to capture affordability, repayment behaviour, credit utilisation, and recovery potential.

Q1(g) Encoding
"""

freq_cols = [
    'sub_grade',
    'state_code',
    'emi_bank_name',
    'primary_enq_purpose',
    'emp_title',
    'primary_cc_bank',
    'top_spend_category',
    'valuation_agency',
    'branch_id'
]

for col in freq_cols:

    freq_map = master_df[col].value_counts(
        normalize=True
    )

    master_df[col + '_freq'] = (
        master_df[col]
        .map(freq_map)
        .astype('float32')
    )

"""Frequency encoding was applied to high-cardinality categorical variables to avoid excessive memory consumption and dimensionality growth.

Q1(h) Final Validation
"""

master_df.shape

master_df.duplicated().sum()

master_df['loan_status'].value_counts(normalize=True)

"""The final dataset contained approximately 2 million observations with no duplicate records. The target variable exhibited substantial class imbalance, with default events representing approximately 3.9% of all loans.

Q1(i) Export Dataset
"""

master_df.to_csv(
    "credit_risk_cleaned.csv",
    index=False
)

"""The dataset was successfully integrated, cleaned, validated, and enriched through feature engineering. Memory-efficient preprocessing techniques were adopted to handle the large-scale dataset while preserving analytical quality and preparing the data for subsequent modelling tasks."""

master_df.to_parquet(
    '/content/drive/MyDrive/cleaned_master_df.parquet',
    index=False
)

