# -*- coding: utf-8 -*-
"""EDA Q2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNEzsjUWbuiPqqtIIDKp7426uZPq98Zf
"""

import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt

master_df = pd.read_parquet(
    '/content/drive/MyDrive/cleaned_master_df.parquet'
)

sample_df = master_df.sample(
    n=200000,
    random_state=42
)

"""Q2(a) Loan Status Distribution"""

status_counts = master_df['loan_status'].value_counts()

plt.figure(figsize=(6,4))
status_counts.plot(kind='bar')
plt.title('Distribution of Loan Status')
plt.xlabel('Loan Status')
plt.ylabel('Number of Loans')
plt.show()

plt.figure(figsize=(6,6))
status_counts.plot(
    kind='pie',
    autopct='%1.2f%%'
)
plt.ylabel('')
plt.title('Loan Status Distribution')
plt.show()

default_rate = (
    master_df['loan_status'].mean()*100
)

print(default_rate)

"""The dataset is highly imbalanced with approximately 3.88% defaulted loans and 96.12% performing loans. Such imbalance may bias predictive models toward the majority class. Common solutions include SMOTE oversampling and class-weighted learning."""

plt.figure(figsize=(8,5))

sns.kdeplot(
    sample_df[
        sample_df['loan_status']==0
    ]['cibil_score'],
    label='Performing'
)

sns.kdeplot(
    sample_df[
        sample_df['loan_status']==1
    ]['cibil_score'],
    label='Default'
)

plt.title('CIBIL Score Distribution')
plt.xlabel('CIBIL Score')
plt.ylabel('Density')
plt.legend()
plt.show()

sample_df.groupby(
    'loan_status'
)['cibil_score'].mean()

g0 = sample_df[
    sample_df.loan_status==0
]['cibil_score']

g1 = sample_df[
    sample_df.loan_status==1
]['cibil_score']

pooled_std = sqrt(
    (
        g0.std()**2 +
        g1.std()**2
    )/2
)

cohens_d = (
    g0.mean()-g1.mean()
)/pooled_std

print(cohens_d)

"""Defaulted borrowers exhibit lower average CIBIL scores. However, substantial overlap remains between the distributions, indicating that CIBIL alone cannot fully discriminate default risk.

Q2(c) 12 Histogram Grid
"""

hist_cols = [
    'loan_amnt_inr',
    'annual_inc_inr',
    'int_rate_pct',
    'installment_inr',
    'dti_pct',
    'cibil_score',
    'revol_bal_inr',
    'revol_util_pct',
    'open_acc',
    'total_acc',
    'loan_income_ratio',
    'emi_income_burden'
]

sample_df[hist_cols].hist(
    figsize=(15,12),
    bins=30
)

plt.suptitle(
    'Distribution of Numeric Variables'
)

plt.show()

# Skewness
sample_df[hist_cols].skew()

# Log Transform
# For skew > 2:
sample_df['annual_inc_log'] = np.log1p(
    sample_df['annual_inc_inr']
)

sample_df['revol_bal_log'] = np.log1p(
    sample_df['revol_bal_inr']
)

sample_df[
    ['annual_inc_log',
     'revol_bal_log']
].skew()

"""Several financial variables exhibited significant right skew due to a small number of extremely large borrowers. Log transformation substantially reduced skewness and improved suitability for regression models.

Q2(d) Correlation Heatmap
"""

corr_cols = sample_df.select_dtypes(
    include=np.number
).columns[:20]

corr = sample_df[
    corr_cols
].corr()

plt.figure(figsize=(12,8))

sns.heatmap(
    corr,
    annot=True,
    fmt='.2f',
    cmap='coolwarm'
)

plt.title(
    'Correlation Matrix'
)

plt.show()

# High Correlation
corr_pairs = corr.abs().unstack()

corr_pairs[
    corr_pairs > 0.75
].sort_values(
    ascending=False
)

"""Highly correlated predictors may cause multicollinearity, inflating coefficient variance and reducing interpretability in OLS regression.

Q2(e) Boxplots
"""

box_cols = [
    'int_rate_pct',
    'dti_pct',
    'cibil_score',
    'annual_inc_inr',
    'revol_util_pct',
    'emp_length_years'
]

fig, axes = plt.subplots(
    2,3,
    figsize=(15,8)
)

for ax,col in zip(
    axes.flatten(),
    box_cols
):

    sns.boxplot(
        x='loan_status',
        y=col,
        data=sample_df,
        ax=ax
    )

plt.tight_layout()
plt.show()

# Median Difference
for col in box_cols:

    med = sample_df.groupby(
        'loan_status'
    )[col].median()

    print(
        col,
        med[1]-med[0]
    )

"""Q2(f) Default Rate by Grade"""

grade_default = master_df.groupby(
    'grade'
)['loan_status'].mean()*100

grade_default = grade_default.sort_index()

grade_default.plot(
    kind='bar'
)

plt.title(
    'Default Rate by Grade'
)

plt.ylabel(
    'Default Rate (%)'
)

plt.show()

grade_default.diff()

"""Default rates increase steadily from Grade A to Grade G, confirming that the internal grading system is risk ordered.

Q2(g) Default Rate by Purpose
"""

purpose_default = (
    master_df.groupby(
        'loan_purpose'
    )['loan_status']
    .mean()
    .sort_values(
        ascending=False
    )*100
)

purpose_default.plot(
    kind='barh',
    figsize=(8,6)
)

plt.title(
    'Default Rate by Loan Purpose'
)

plt.show()

# Highest & Lowest
purpose_default.head(3)

purpose_default.tail(2)

"""Q2(h) State-Level Default Rate"""

state_default = (
    master_df.groupby(
        'state_code'
    )['loan_status']
    .mean()
    *100
).sort_values(
    ascending=False
)

state_default.head(10).plot(
    kind='bar'
)

plt.title(
    'Top 10 States by Default Rate'
)

plt.ylabel(
    'Default Rate (%)'
)

plt.show()

"""Q2(i) Annual Default Trend"""

annual_default = (
    master_df.groupby(
        'issue_year'
    )['loan_status']
    .mean()
    *100
)

annual_default.plot(
    marker='o'
)

plt.title(
    'Annual Default Rate'
)

plt.ylabel(
    'Default Rate (%)'
)

plt.show()

# COVID Shock
covid_jump = (
    annual_default.loc[2020]
    -
    annual_default.loc[2019]
)

print(covid_jump)

"""Q2(j) Repo Rate vs Default Rate"""

repo = master_df.groupby(
    'issue_year'
)['rbi_repo_rate_pct'].mean()

defaults = master_df.groupby(
    'issue_year'
)['loan_status'].mean()*100

fig, ax1 = plt.subplots()

ax1.plot(
    repo.index,
    repo.values
)

ax2 = ax1.twinx()

ax2.plot(
    defaults.index,
    defaults.values
)

plt.title(
    'Repo Rate vs Default Rate'
)

plt.show()

"""Q2(k) LGD Distribution"""

defaults = sample_df[
    sample_df.loan_status==1
]

sns.histplot(
    defaults['lgd_pct'],
    kde=True
)

plt.title(
    'LGD Distribution'
)

plt.show()

"""Examine whether the distribution is symmetric, skewed, unimodal, or bimodal. If strongly right-skewed, a log transformation may improve modelling performance.

Q2(l) CIBIL vs LGD
"""

from scipy.stats import pearsonr

r, p = pearsonr(
    defaults['cibil_score'],
    defaults['lgd_pct']
)

print(r)

sns.regplot(
    x='cibil_score',
    y='lgd_pct',
    data=defaults
)

plt.title(
    'CIBIL Score vs LGD'
)

plt.show()

"""A negative correlation indicates that borrowers with stronger credit histories tend to experience lower loss severity when default occurs."""