# -*- coding: utf-8 -*-
"""EDA Q4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5mD2__EgMoalrUGxy35C5ne3dDtv8MR
"""

import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt
from scipy.stats import ttest_ind
from statsmodels.stats.outliers_influence import variance_inflation_factor

master_df = pd.read_parquet(
    '/content/drive/MyDrive/Q3_feature_engineered.parquet'
)

"""Create Modelling Dataset"""

df_model = master_df[
    master_df['loan_status']==1
].copy()

# Remove Leakage Variables
leakage_cols = [
    'total_pymnt_inr',
    'total_pymnt_inv_inr',
    'recoveries_inr',
    'collection_recovery_fee',
    'net_loss_inr'
]

df_model = df_model.drop(
    columns=leakage_cols,
    errors='ignore'
)

"""Q4(a) VIF Analysis"""

# Select Numeric Features
# Exclude target.
num_cols = df_model.select_dtypes(
    include=np.number
).columns.tolist()

num_cols.remove('lgd_pct')
num_cols.remove('loan_status')

# Fill Missing Values
X = df_model[num_cols].fillna(
    df_model[num_cols].median()
)

X_vif = X.sample(
    n=10000,
    random_state=42
)

print(X_vif.shape)

# Calculate VIF
vif_df = pd.DataFrame()

vif_df['Feature'] = X.columns

vif_df['VIF'] = [
    variance_inflation_factor(
        X.values,
        i
    )
    for i in range(X.shape[1])
]

vif_df.sort_values(
    'VIF',
    ascending=False
)
vif_df

high_vif = vif_df[
    vif_df['VIF'] > 10
]
print(high_vif)

features_keep = vif_df[
    vif_df['VIF'] <= 10
]['Feature'].tolist()

X = X[features_keep]
print(X.shape)

"""Variance Inflation Factors (VIF) were computed to detect multicollinearity among predictors. Variables with VIF values greater than 10 were removed because they contain redundant information already captured by other variables. The remaining variables exhibited acceptable levels of multicollinearity and were retained for modelling.

Q4(b) OLS Regression
"""

import statsmodels.api as sm

X_const = sm.add_constant(X)

y = df_model['lgd_pct']

ols_model = sm.OLS(
    y,
    X_const
).fit()

print(
    ols_model.summary()
)

"""R² --

R² indicates the proportion of variation in LGD explained by the model.

Adjusted R² --

Adjusted R² accounts for the number of predictors and provides a more realistic measure of model performance.

F Statistic --

The F-test evaluates whether the model provides significantly better explanatory power than a model with no predictors.

Durbin-Watson

Close to 2

Residuals appear independent.

Jarque-Bera

p < 0.05

Residuals deviate from normality.

or

p > 0.05

Residuals are approximately normal.

Condition Number

<30 --> Good

greater than 100 -->
Possible multicollinearity

Largest Coefficients
"""

coef_df = pd.DataFrame({
    'Feature': ols_model.params.index,
    'Coef': ols_model.params.values
})

coef_df.reindex(
    coef_df['Coef']
    .abs()
    .sort_values(
        ascending=False
    ).index
).head(5)

"""Q4(c) Ridge, Lasso, ElasticNet"""

print(X.shape)
print(y.shape)

# Train-Test Split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Ridge"""

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

ridge_grid = GridSearchCV(
    Ridge(),
    {'alpha':[0.01,0.1,1,10,100]},
    cv=5,
    scoring='neg_root_mean_squared_error'
)

ridge_grid.fit(
    X_train,
    y_train
)

"""Lasso"""

from sklearn.linear_model import Lasso

lasso_grid = GridSearchCV(
    Lasso(max_iter=5000),
    {'alpha':[0.001,0.01,0.1,1]},
    cv=5,
    scoring='neg_root_mean_squared_error'
)

lasso_grid.fit(
    X_train,
    y_train
)

"""ElasticNet"""

from sklearn.linear_model import ElasticNet

enet_grid = GridSearchCV(
    ElasticNet(max_iter=5000),
    {
        'alpha':[0.001,0.01,0.1,1],
        'l1_ratio':[0.2,0.5,0.8]
    },
    cv=5,
    scoring='neg_root_mean_squared_error'
)

enet_grid.fit(
    X_train,
    y_train
)

"""Test R²"""

ridge_r2 = r2_score(
    y_test,
    ridge_grid.predict(X_test)
)

lasso_r2 = r2_score(
    y_test,
    lasso_grid.predict(X_test)
)

enet_r2 = r2_score(
    y_test,
    enet_grid.predict(X_test)
)

comparison = pd.DataFrame({
    'Model':['Ridge','Lasso','ElasticNet'],
    'Best Alpha':[
        ridge_grid.best_params_,
        lasso_grid.best_params_,
        enet_grid.best_params_
    ],
    'Test R2':[
        ridge_r2,
        lasso_r2,
        enet_r2
    ]
})

comparison

lasso_model = lasso_grid.best_estimator_

zero_features = X.columns[
    lasso_model.coef_==0
]

print(zero_features)

"""Ridge, Lasso, and ElasticNet were evaluated using five-fold cross-validation. Hyperparameters were selected using GridSearchCV. Lasso additionally performed feature selection by shrinking some coefficients exactly to zero, indicating limited predictive contribution from those variables.

Q4(d) Diagnostic Plots
"""

# Residuals
residuals = (
    y -
    ols_model.predict(X_const)
)

# 4 Panels
fig = plt.figure(
    figsize=(15,10)
)

# 1 Residual vs Fitted
plt.subplot(221)

plt.scatter(
    ols_model.fittedvalues,
    residuals
)

"""This plot assesses linearity. Random scatter indicates that the linearity assumption is reasonably satisfied."""

# QQ Plot
plt.subplot(222)

sm.qqplot(
    residuals,
    line='45',
    fit=True
)

"""This plot evaluates residual normality. Deviations from the diagonal line suggest departures from normality."""

#  Scale Location
plt.subplot(223)

plt.scatter(
    ols_model.fittedvalues,
    np.sqrt(
        abs(residuals)
    )
)

"""This plot examines homoscedasticity. A random pattern indicates approximately constant variance."""

# Cook's Distance
plt.subplot(224)

influence = ols_model.get_influence()

cooks = influence.cooks_distance[0]

plt.stem(cooks)

"""This plot identifies influential observations. Large Cook's Distance values indicate observations with disproportionate influence on model estimates."""