# -*- coding: utf-8 -*-
"""EDA Q3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLre050eWM4HdJ100SA3YhIl4oh1CyTR
"""

import pandas as pd
import numpy as np
import os
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from math import sqrt
from scipy.stats import ttest_ind
from statsmodels.stats.outliers_influence import variance_inflation_factor

master_df = pd.read_parquet(
    '/content/drive/MyDrive/cleaned_master_df.parquet'
)

"""Q3(a) Repayment Burden Features"""

# Feature 1: EMI to Income Ratio
master_df['emi_to_income_ratio'] = (
    master_df['installment_inr']
    /
    ((master_df['annual_inc_inr']/12) + 1)
)

"""The EMI-to-Income Ratio was calculated as monthly installment divided by monthly income. This feature measures the proportion of borrower income committed toward loan repayment."""

master_df['emi_to_income_ratio'].describe()

master_df[
    ['emi_to_income_ratio','lgd_pct']
].corr(method='pearson')

"""Higher EMI burden means a larger share of income is committed to debt repayment, increasing financial stress and potential loss severity."""

# Feature 2: Loan to Income Ratio
master_df['loan_to_income_ratio'] = (
    master_df['loan_amnt_inr']
    /
    (master_df['annual_inc_inr'] + 1)
)

"""The Loan-to-Income Ratio was constructed by dividing sanctioned loan amount by annual borrower income. This feature captures leverage at the time of loan origination."""

master_df[
    ['loan_to_income_ratio','lgd_pct']
].corr()

"""Large loans relative to borrower income generally imply greater repayment risk."""

# Feature 3: Rate Spread
master_df['rate_spread_feature'] = (
    master_df['int_rate_pct']
    -
    master_df['rbi_repo_rate_pct']
)

"""Rate Spread was calculated as the difference between the borrower interest rate and the prevailing RBI repo rate. This feature measures the additional risk premium charged by the lender."""

master_df[
    ['rate_spread_feature','lgd_pct']
].corr()

"""A higher spread often reflects higher perceived borrower risk."""

# Feature 4: Real Interest Rate
master_df['real_interest_rate_feature'] = (
    master_df['int_rate_pct']
    -
    master_df['cpi_inflation_pct']
)

"""Real Interest Rate was computed as the nominal interest rate less CPI inflation. This variable reflects the effective borrowing cost after accounting for inflation."""

# Correlations
master_df[
    ['real_interest_rate_feature','lgd_pct']
].corr()

# Compare All Four
features_a = [
    'emi_to_income_ratio',
    'loan_to_income_ratio',
    'rate_spread_feature',
    'real_interest_rate_feature'
]

for col in features_a:
    corr = master_df[col].corr(master_df['lgd_pct'])
    print(col, round(corr,4))

"""Among the four repayment-burden features, the variable with the highest absolute Pearson correlation was identified as the strongest predictor of LGD. This feature demonstrates the strongest linear association with loss severity and may provide additional explanatory power in subsequent modelling stages.

Q3(b) Bureau Behaviour Features
"""

# Credit Utilisation Composite
master_df['credit_util_composite'] = (
    0.5*master_df['revol_util_pct']
    +
    0.3*master_df['bc_util_pct']
    +
    0.2*master_df['all_util_pct']
)

"""A composite credit utilisation measure was created using weighted utilisation metrics from revolving, bankcard, and overall credit facilities."""

# Delinquency Severity Score
master_df['delinq_severity_score'] = (
    master_df['delinq_2yrs']
    *
    (
        1
        +
        1 /
        master_df[
            'mths_since_last_delinq'
        ].clip(lower=1)
    )
)

"""Delinquency Severity Score combines the number of historical delinquencies with recency information."""

# Enquiry Velocity Score
master_df['enq_velocity_score'] = (
    4*master_df['num_enquiries_30d']
    +
    master_df['num_enquiries_90d']
)

"""Enquiry Velocity Score measures recent credit-seeking behaviour by assigning greater weight to enquiries made within the previous 30 days.The feature was constructed to capture short-term changes in borrower credit demand and assessed against LGD."""

# Correlations
features_b = [
    'credit_util_composite',
    'delinq_severity_score',
    'enq_velocity_score'
]

for col in features_b:
    print(
        col,
        master_df[col].corr(
            master_df['lgd_pct']
        )
    )

"""Q3(c) Income & Collateral Features"""

# Income Stability Ratio
master_df['income_stability_ratio'] = (
    master_df['annual_inc_inr']
    /
    (
        master_df['emp_length_years']
        + 1
    )
)

"""Income Stability Ratio was calculated by dividing annual income by employment tenure. The feature attempts to capture income consistency over the borrower’s employment history."""

# Credit Depth Score
master_df['credit_depth_score'] = (
    master_df['total_acc']
    /
    (
        master_df['credit_hist_years']
        + 1
    )
)

"""Credit Depth Score measures the number of credit accounts relative to credit history length. This feature captures the breadth of borrower credit experience."""

# Collateral Coverage Ratio
master_df['collateral_coverage_ratio'] = (
    master_df['collateral_value_inr']
    /
    (
        master_df['loan_amnt_inr']
        + 1
    )
)

"""Collateral Coverage Ratio was calculated as collateral value divided by loan amount. This feature measures the extent to which collateral can absorb potential losses in the event of default."""

# Correlations
features_c = [
    'income_stability_ratio',
    'credit_depth_score',
    'collateral_coverage_ratio'
]

for col in features_c:
    print(
        col,
        master_df[col].corr(
            master_df['lgd_pct']
        )
    )

"""Q3(d) Log Transformation"""

# Before
print(
    master_df['annual_inc_inr'].skew()
)

print(
    master_df['loan_amnt_inr'].skew()
)

# Create Features
master_df['log_annual_inc'] = np.log1p(
    master_df['annual_inc_inr']
)

master_df['log_loan_amnt'] = np.log1p(
    master_df['loan_amnt_inr']
)

# After
print(
    master_df['log_annual_inc'].skew()
)

print(
    master_df['log_loan_amnt'].skew()
)

"""Q3(e) COVID Flag & T-Test"""

# Create Flag
master_df['covid_issue_year_flag'] = (
    master_df['issue_year']
    == 2020
).astype(int)

# Summary
master_df.groupby(
    'covid_issue_year_flag'
)['lgd_pct'].mean()

"""T-Test"""

covid = master_df[
    master_df['covid_issue_year_flag']==1
]['lgd_pct']

non_covid = master_df[
    master_df['covid_issue_year_flag']==0
]['lgd_pct']

t_stat,p_value = ttest_ind(
    covid,
    non_covid,
    equal_var=False
)

print(p_value)

"""Create Modelling Dataset"""

df_model = master_df[
    master_df['loan_status']==1
].copy()

# Remove Leakage Variables
leakage_cols = [
    'total_pymnt_inr',
    'total_pymnt_inv_inr',
    'recoveries_inr',
    'collection_recovery_fee',
    'net_loss_inr'
]

df_model = df_model.drop(
    columns=leakage_cols,
    errors='ignore'
)

"""Q4(a) VIF Analysis"""

# Select Numeric Features
# Exclude target.
num_cols = df_model.select_dtypes(
    include=np.number
).columns.tolist()

num_cols.remove('lgd_pct')
num_cols.remove('loan_status')

# Fill Missing Values
X = df_model[num_cols].fillna(
    df_model[num_cols].median()
)

X_vif = X.sample(
    n=10000,
    random_state=42
)

print(X_vif.shape)

# Calculate VIF
vif_df = pd.DataFrame()

vif_df['Feature'] = X.columns

vif_df['VIF'] = [
    variance_inflation_factor(
        X.values,
        i
    )
    for i in range(X.shape[1])
]

vif_df.sort_values(
    'VIF',
    ascending=False
)
vif_df

high_vif = vif_df[
    vif_df['VIF'] > 10
]
print(high_vif)

features_keep = vif_df[
    vif_df['VIF'] <= 10
]['Feature'].tolist()

X = X[features_keep]
print(X.shape)

"""Variance Inflation Factors (VIF) were computed to detect multicollinearity among predictors. Variables with VIF values greater than 10 were removed because they contain redundant information already captured by other variables. The remaining variables exhibited acceptable levels of multicollinearity and were retained for modelling."""

master_df.to_parquet(
    '/content/drive/MyDrive/Q3_feature_engineered.parquet',
    index=False
)